"""Stage a reviewed road candidate; never register it or replace accepted data."""
import argparse
import hashlib
import json
from pathlib import Path
import shutil

ROOT = Path(__file__).resolve().parents[2]


def stage(candidate, rendered, cue_path):
    manifest = json.loads((candidate/'measurement_manifest_candidate.json').read_text())
    source_result = json.loads((candidate/'result.json').read_text())
    result = json.loads((rendered/'results.json').read_text())
    if not source_result['passed'] or not result['finished'] or not result['reports']['passed'] or result['errors_seen'] or result['frame_warnings']:
        raise ValueError('Source and rendered candidate gates must pass first')
    if not (rendered/'process-exit.txt').exists():
        raise ValueError('Rendered test process exit receipt required')
    cue = json.loads(cue_path.read_text())
    if cue['source_sha256'] != manifest['source_sha256']:
        raise ValueError('Start cue belongs to a different source')
    if max(cue['gate_edge_plane_residuals']) >= cue['stripe_half_width']:
        raise ValueError('Timing gate does not fit the measured source stripe')
    source = Path(manifest['source'])
    if hashlib.sha256(source.read_bytes()).hexdigest() != manifest['source_sha256']:
        raise ValueError('Source changed since extraction')
    for selection in ('visible_meshes', 'collision_meshes'):
        if not manifest.get(selection): raise ValueError(f'Reviewed {selection} required')
    course = manifest['id']
    base = ROOT/'tracks'/course
    asset = ROOT/'assets/imported/tabletop'/f'{course}.glb'
    if base.exists() or asset.exists():
        raise ValueError('Course already staged; accepted data is never overwritten')
    rows = json.loads((candidate/'measured_candidate.json').read_text())
    if not rows or len(rows)%24: raise ValueError('Invalid measured rows')
    if not 0 <= cue['start_station'] < manifest['geometry_checks']['length']:
        raise ValueError('Start station outside measured route')
    metadata = manifest['source_metadata']['extras']
    manifest.update(start_station=cue['start_station'], source_start_cue=cue,
                    start_cue='Original source checker stripe; measured timing plane and FINISH flags',
                    height_surfaces=manifest['road_meshes'], unresolved_intervals=[], uncertainty=[],
                    physics_support_tolerance=manifest['height_tolerance'],
                    section_count=len(rows)//24, route_sample_count=len(rows),
                    source_url=metadata['source'], author=metadata['author'], license=metadata['license'],
                    status='source and rendered candidate accepted; playable acceptance pending')
    checkpoint = candidate/'pre-staging'
    checkpoint.mkdir(exist_ok=False)
    hashes = {str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest()
              for p in (ROOT/'tracks').glob('*/measured_route.json')}
    (checkpoint/'accepted-route-hashes.json').write_text(json.dumps(hashes,indent=2))
    for relative in ('scripts/tracks/content_catalog.gd','scripts/tracks/selected_course.gd',
                     'scripts/race/asset_credits.gd','assets/imported/tabletop/CREDITS.md'):
        shutil.copy2(ROOT/relative,checkpoint/Path(relative).name)
    base.mkdir()
    (base/'measurement_manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
    shutil.copy2(candidate/'measured_candidate.json',base/'measured_route.json')
    shutil.copy2(candidate/'road_boundaries.json',base/'road_boundaries.json')
    shutil.copy2(source,asset)
    # Seed explicit import parameters before the editor first sees the new asset.
    # Remap/dependency/UID values are generated by Godot for this new path.
    (Path(str(asset)+'.import')).write_text('[remap]\nimporter="scene"\n\n[params]\nmeshes/force_disable_compression=true\n')
    return {'course':course,'rows':len(rows),'start_station':cue['start_station'],
            'registered':False,'next':'Import asset, author resources, then verify playable course before catalogue registration'}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('candidate',type=Path)
    parser.add_argument('rendered',type=Path)
    parser.add_argument('cue',type=Path)
    args = parser.parse_args()
    print(json.dumps(stage(args.candidate,args.rendered,args.cue)))
