extends "res://tests/autopilot/probe_base.gd"
func _ready() -> void:
	await super._ready()
	await settle(5)
	var race: Node3D = get_tree().current_scene.get_node("Race")
	race.profile.read_only = true
	race.controller.set_process_input(false)
	race.controller.set_physics_process(false)
	race.controller.device = -1
	race.controller.using_pad = false
	save_frame("menu")
	race.start_race()
	await settle(3)
	save_frame("staging")
	race.begin_countdown()
	await settle(3)
	save_frame("countdown")
	race.toggle_pause()
	await settle(3)
	save_frame("paused")
	report("pause",race.paused_race)
	race.toggle_pause()
	race.session.change_phase(3)
	race.trial.result_note = "NEW PERSONAL BEST · 88.52s\nBEST LAP · 28.24s"
	var rows: Array = []
	for i: int in range(4): rows.append({"rank":i+1,"player":i+1,"finished":true,"time":88.52+i*1.45,"laps":3,"penalty":5.0 if i==2 else 0.0})
	race.on_results_ready(rows)
	await settle(3)
	save_frame("results")
	report("results_focus",get_viewport().gui_get_focus_owner()==race.results_panel.get_node("Retry"))
	report("text_fits",race.banner.get_minimum_size().y<=race.banner.size.y)
	race.get_node("Retro").hide()
	DisplayServer.window_set_size(Vector2i(960,640))
	await settle(4)
	save_frame("results_960_no_pixels")
	DisplayServer.window_set_size(Vector2i(1600,900))
	race.get_node("Retro").show()
	await settle(4)
	save_frame("results_1600_pixels")
	race.results_panel.get_node("Menu").pressed.emit()
	await settle(3)
	report("menu_action",race.phase==0 and race.menu.visible and not race.results_panel.visible)
	report("passed",_reports.pause and _reports.results_focus and _reports.text_fits and _reports.menu_action)
	finish()
